version: '3.3'

services:
  db:
    # Using enterprise for more constraint features
    image: neo4j:4.0-enterprise
    restart: always

    environment:
      # Required in order to use the enterprise version
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      # Basic auth changes
      NEO4J_AUTH: neo4j/j4oen

    ports:
      - 7474:7474 # http access
      - 7687:7687 # bolt access

    volumes:
      - ./data:/data # Allows our database data not to reset if the service is tore down
      - ./scripts:/scripts # Mounts our scripts for running in the container
